= Development process

== Overview
The code for Phantom 8 can be found at link:https://github.com/vthps/Phantom8[]

There is a vthps organization where different repositories for different submarines could one day exist. For now there is just the Phantom 8 repository. 

The master branch is for the latest most up-to-date functioning code. The master branch is for code that is ready to be used. If code is put together to test the battery, when this code is ready to be used it should be put in the master branch. Another example is at competition the master branch should contain the final race code. 

Code that was brought over to github from Google drive not in a finished state is moved into the _in-progress_ branch. 

When working on part of the project, create a new branch with your name and what it is you are doing. For example, _linearactuator-ben_ . Work on the code and when it is complete make a pull request to the master branch. In the pull request make sure to say what you did and how it was tested. Someone else on the team, must give a thumbs up to the pull request before it can be merged to master. 

After merging to master, delete the old branch. 


== Proof of understanding

Do the following to show you understand how the development process works.

. Create a new branch called _pou-yourname_ where yourname is replaced with a name that identifies you personally (for example: cgoertel)
. Go under the *Contacts* folder and create a document with your github username in it (each person will have created a separate file). Name the file with your username.
. Commit this document to your branch and have the commit message be:
+
----
I wrote my username in the Contacts folder!
----
+
. Create a pull request to the master branch with these new changes. In the pull request message choose another user and tell that person you added your file and are ready to build P8. 
+
----
@selimodok I added my proof of understanding document and am excited to build Phantom 8!
----
+
. If you are tagged in a pull request(pr) make sure the person who tagged you did what they said they did and give them a thumbs up!

. Once your pr has a thumbs up, go ahead and merge your pr and delete the new branch you had just created.
